### ISSUE TITLE
Add SJJB map icons

### ISSUE THREAD

**Issue by PanderMusubi** [Xaviju/inkscape-open-symbols#39]
Please, add SJJB map icons from http://www.sjjb.co.uk/mapicons/contactsheet Note, these are also used by OpenStreetMap

**Comment by PanderMusubi** [comment]
PS The project is not dead, only that particular repo is.

**Comment by Xaviju** [comment]
I've been trying to convert this icons, but the SVG code is basically unusable without previous work. It could be used as an Inkscape editable, but not as an SVG icon. It will take ages to convert them to symbols manually.
Basically, each icon has multiple stacked paths and shapes. Most of them could be converted to a single path.
If someone has the time to convert the symbols, I'll be happy to mentorize or help in the conversion.

**Comment by Moini** [comment]
@Xaviju: 
- There are some three-color icons in the set. What should be done with those? (use opacity to get the third color?)
- Should all paths of the same color in an icon be unioned?
- Stroke to path is probably fine for most cases, right?
- Should the outside strokes of the squares be removed?
- I'd make two versions: one white with dark square in bg, one dark, without the square. Which colors should be assigned to them in Inkscape? 
- Is a uniform size for the non-square items, e.g. by adding a transparent rectangle, desirable?

**Comment by Xaviju** [comment]
Wow, you have almost created a symbol creation FAQ @Moini 

- There are some three-color (and even four-color) icons in the set. What should be done with those? (use opacity to get the third color?)
I'd rather use opacity instead of color. Only use the color when absolutely required by the icon.

- Should all paths of the same color in an icon be unioned?
Yes if possible. It reduces the icon size. See what [SVGO](https://jakearchibald.github.io/svgomg/) does.

- Stroke to path is probably fine for most cases, right?
In this case I'd say yes. In most cases stroke should be removed.

- Should the outside strokes of the squares be removed?
Yes if possible. I remove all strokes from icons. In this case the image is much complicated so it depends on how necessary are to understand the image. If its not required, please remove it.

- I'd make two versions: one white with dark square in bg, one dark, without the square. Which colors should be assigned to them in Inkscape?
When an icon has no color assigned at all, Inkscape renders it in black. That's for most of the cases. In this case, seems to me that:
    - **Dark square in background:** should be merged in a single path, using the background color as a reference and excluding the icons.
    - **Dark without square:** Remove all references to style in the path or the symbol (except opacity if required) and it wll be rendered in black.

- Is a uniform size for the non-square items, e.g. by adding a transparent rectangle, desirable?
It depends on the set. For the web, i would say yes, but for the designers, I'd say no. I try to keep the original viwebox of the iconset. Please don't add transparent images if will not be rendered, better play with the canvas size (AKA viewbox).

- Should there be any groups?
Groups are not useful for a symbol in Inkscape so it can be removed.

Thanks a lot for your help, I know this is a lot of work. :100:

**Comment by Moini** [comment]
Thx!

I'm almost done with the easy ones ;-) (i.e. those with just two colors, didn't look at the other ones before I knew what to do with them).

As I'm not too keen on doing the final conversion to symbol set myself .... - what would be the best format to 'transfer' the data to you?

Currently, all images are in separate files. I'd make two for each symbol (with/without square), and would keep the folder structure (separate directory tree for each of the two sets).

Would that be sufficient for you to run the auto-creation script on? 

I suspect that, once everything is ungrouped, colors unset or white, shape-forming strokes turned to paths, things unioned, all other strokes set to None, etc., svgo won't cause any errors.

**Comment by Moini** [comment]
Oh, and this I didn't understand:

"Dark square in background: should be merged in a single path, using the background color as a reference and excluding the icons."

- You mean, keep its square shape (which I would have done) or punch an icon-shaped hole into the middle (possible interpretation of the above, but weird to me, sorry for asking)?

**Comment by Moini** [comment]
... and one more: the files don't have a viewbox, only width and height. Inkscape adds one if you copy-paste into a new document, but that comes with an additional layer... Do you have a suggestion how this can be done quickly from within Inkscape? (yes, I know I could script it...)

**Comment by Moini** [comment]
Save as -> Optimized SVG, check 'enable viewboxing'. Okay?

**Comment by Moini** [comment]
Test set attached. Would this be the right way to go on?

[Icons.zip](https://github.com/Xaviju/inkscape-open-symbols/files/674356/Icons.zip)

**Comment by Xaviju** [comment]
I'll try to look at the code tomorrow morning, but I answer your questions:

-  **what would be the best format to 'transfer' the data to you?**
To me the best way would be a pull request with all the icons in a new folder with both subsets. Attaching a ZIP as you just did its OK as well.

 - **punch an icon-shaped hole into the middle (possible interpretation of the above, but weird to me, sorry for asking)**
Yes, I meant that, is what many iconsets do. Otherwise, one layer has to have a fill or stroke. If you remove the styles in all paths (rects, circles) when you put an path in top of another, it will be black on Inkscape (try it). If you keep the style, the user won't be able to edit it. In some cases, like in the Emoji One symbol set, for example, this makes sense.

- Save as -> Optimized SVG, check 'enable viewboxing'. Okay?
Sounds good. :)

**Comment by Xaviju** [comment]
I've read the icons.zip code, amazing work. :)

I found some small to fix you'll see below. I've created a branch with the icons so you can work on them: https://github.com/Xaviju/inkscape-open-symbols/pull/51/files

- this code can be removed
```
<g transform="matrix(48.14969,0,0,48.14969,-1513.4809,-137.68495)" stroke="#757575" stroke-width=".1" display="none" fill="none">
<rect display="inline" height="10" width="10" y="1" x="1"/>
<rect display="inline" height="8" width="8" y="2" x="2"/>
</g>
```
- all the _style_ attributes should be removed if are not for opacity. 
```
style="color-rendering:auto;text-decoration-color:#000000;color:#000000;isolation:auto;mix-blend-mode:normal;shape-rendering:auto;solid-color:#000000;block-progression:tb;text-decoration-line:none;text-decoration-style:solid;image-rendering:auto;white-space:normal;text-indent:0;text-transform:none"
```
- all the _fill_ attributes should be removed if are not for opacity. 
```
fill-rule="evenodd"
```

**Comment by Moini** [comment]
There aren't any holes punched into them... I was going to make a third set with those holes instead of white on unset background color, but that would take quite a lot of time. If it's sufficient like this, then I'll defer creation of that set for a bit.

Do you already have some shell script maybe, that does the style cleanup? It must be done manually after working on the files in Inkscape (else I'll write one, probably python, then, though).

**Comment by Xaviju** [comment]
@Moini I see, no problem, it makes sense as is now without the holes. :+1: 

It won't be too difficult to remove the styles with minor changes in the gulpfile https://github.com/Xaviju/inkscape-open-symbols/blob/master/gulpfile.js I can do that.

**Comment by Moini** [comment]
Thank you, @Xaviju . I'm almost through with the square ones, only two folders missing.

**Comment by PanderMusubi** [comment]
Very good work. Also let the latest contributers upstream know about this. Perhaps also mention it and this project in the OpenStreetMap wiki where there is an article on map icon sets.

**Comment by Moini** [comment]
The square svgs are up here: https://github.com/Moini/inkscape-open-symbols/tree/sjjb-icons
I'll make a pull request when the others are ready, too.

**Comment by Moini** [comment]
@PanderMusubi : when the icon sets are done, would you do any contacting / news spreading yourself? It seems you already know exactly who would be interested :)

**Comment by PanderMusubi** [comment]
Yes, no problem

**Comment by Moini** [comment]
@PanderMusubi : Thanks!

**Comment by PanderMusubi** [comment]
See also https://github.com/Xaviju/inkscape-open-symbols/pull/52

**Comment by PanderMusubi** [comment]
@Moini, I have send an BCC email to those responsible for original SJJB icons and all late forks from where I could find email addresses. Also I have added links on three pages in the OSM wiki on map icons.

**Comment by Moini** [comment]
Thank you, Pander :)

**Comment by Xaviju** [comment]
Hey @Moini I've seen that some sprites mixed square and inverted icons in a single sprite. I didn't expected it, but I thinks its not a bad idea. A single file for both square and inverted icons so, in the end, the whole set will consist only of 16 sprites. 
See how it looks:
![screenshot from 2017-01-07 22-12-51](https://cloud.githubusercontent.com/assets/1343702/21745213/782fecc8-d526-11e6-9979-8bc9fdd08acd.png)

Would you expect to have separate files or does it look ok as in the screenshot? It seems better to me.

**Comment by Moini** [comment]
Should the order be changed? In the other 'sprites' (aka symbol sets) they've made it so the corresponding icons are next to each other. 

Not sure what's better, though, from a user point of view. It certainly looks calmer this way, but for the large sets, alphabet ordering is easier to navigate, and icons of the second kind (in the case of the screenshot, the inverted ones) are found more easily. Do you have a preference based on experience rather than my 'guessing'?

I actually hoped that they will to come together into one, so that's great :) (drop-down menus are harder to navigate than the picture scrolling).

**Comment by Xaviju** [comment]
It makes sense to have corresponding icons together. 
Since it is a lot of work, first release could display both sets in the same sprite and after that we could reorder it to improve the UX. I'm working on it. 
Great work btw, it's a pleasure to work on this cleaned set. :)

**Comment by Moini** [comment]
That sounds fine to me - thank you!

**Comment by Xaviju** [comment]
@PanderMusubi  @Moini new symbol sets are here: https://github.com/Xaviju/inkscape-open-symbols/tree/master/sjjb
Could you please test it and ensure it works as expected?

Thanks.

@Moini amazing work. It was really easy to work with the SVGs you created. Very few bugs for so large iconset. Thanks.

**Comment by PanderMusubi** [comment]
They work for me. One minor change for the entries in the Symbol set pull down selection, rename "SJJB icons [..." to "SJJB Map Icons [..."

The usage of capitals is conform other entries in that list and the addition of Map explains a bit more on the origin of these symbols.

**Comment by Xaviju** [comment]
Renamed!

**Comment by Moini** [comment]
@Xaviju : It appears to work very well :) Thank you for helping me with them!

Does anyone happen to understand how the icon sets are sorted in the dropdown? They are in seemingly random order for me.

**Comment by PanderMusubi** [comment]
the order needs improving indeed. No idea how that is ordered.

**Comment by Xaviju** [comment]
Thanks both!

Yeah, symbols order does not makes sense to me, and when the set is large enough, it can be frustrating.
I was thinking of suggestion on the inkscape blueprints a text filtering of the symbol sets in the top of the box. Something like the [_datalist_ tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) in HTML. What do you think?

**Comment by Moini** [comment]
Definitely, filtering symbols, even if just by their name, would be a nice addition to the dialog (even better if it would then allow you to see symbols from different sets with the same meaning).

**Comment by Moini** [comment]
Bug report for the ordering: https://bugs.launchpad.net/inkscape/+bug/1654902

Filtering seems more involved ;-)

**Comment by PanderMusubi** [comment]
Voted for it, also my colleagues. Here are some (sort of) related Inkscape bugs to vote for, if you would:
* https://bugs.launchpad.net/inkscape/+bug/1620610 (also related to filtering)
* https://bugs.launchpad.net/ubuntu/+bug/1464270
* https://bugs.launchpad.net/inkscape/+bug/741856
* https://bugs.launchpad.net/inkscape/+bug/1374870
* https://bugs.launchpad.net/inkscape/+bug/1574518
* https://bugs.launchpad.net/inkscape/+bug/171869

**Comment by su-v** [comment]
Pander also filed:
* Display icons with name in alphabetically sorted list in symbols dock  
  https://bugs.launchpad.net/inkscape/+bug/1514481

**Comment by PanderMusubi** [comment]
Ah, yeah. And even put a bounty on it.

**Comment by PanderMusubi** [comment]
To further (ab)use this issue now I have found my audience, also for most of us is to vote for https://bugs.launchpad.net/inkscape/+bug/1512175

**Comment by Xaviju** [comment]
@PanderMusubi althought this could be interesting for some of us, please try to share only relevant information for the issue, otherways watchers might be receiveng undesired emails. Thanks!

**Comment by jabiertxof** [comment]
I think symbols need to be updated on the files instad overload the user computer. A script can be done to order It.maybe a inkscape extension and after it export as plain svg to reduce pageload.
